name: Deploy tursim

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to VPS
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            cd tursim
            git pull
            export NVM_DIR=~/.nvm
            source ~/.nvm/nvm.sh 
            npm i
            npm run build
            cd ~
            docker compose restart
